[package]
name = "paginator-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
paginator-rs.workspace = true
paginator-utils.workspace = true
serde.workspace = true
serde_json.workspace = true
